### ISSUE TITLE
Add data recorded (with timestamp) to a file

### ISSUE THREAD

**Issue by TheBlocks** [TheBlocks/AstroMilano#13]
One of the requirements is that we have to add every single piece of data we record to a file. We also need to add a timestamp.

For example, it could look like this:
18-03-17 14:32:54 Humidity: 45%
18-03-17 14:32:54 Temperature: 25 Celsius
18-03-17 14:32:55 Humidity: 46%
18-03-17 14:32:55 Temperature: 25 Celsius

(Don't remove this issue)

**Comment by TheBlocks** [comment]
Slightly better looking format:

**_18-03-17_**

_14:32:54_
Humidity: 45%
Temperature: 25 Celsius

_14:32:55_
Humidity: 46%
Temperature: 25 Celsius

**Comment by MobFactory** [comment]
While it is better formatting I don't think we should go with it because the first 1 is more easily read by a computer which will be reading the data but i think it would be best of all if we could form a table:
Date           Time           Humidity (%)     Temp (°C)
18/03/17    14:32:54     45                       25

Naturally You would make it an actual table not like the one above.
Its easy to read for a human and super easy to read for a computer. The best balance really...

**Comment by TheBlocks** [comment]
What about a .CSV or json file?

**Comment by MobFactory** [comment]
.CSV is the most light weight, but json is more reliable idk u decide.

**Comment by TheBlocks** [comment]
Let's use .cvs
There's a module that makes it super easy. It's called... csv

**Comment by TheBlocks** [comment]
I'm working on this right now.
