### ISSUE TITLE
Huge file sizes for keeping records

### ISSUE THREAD

**Issue by TheBlocks** [TheBlocks/AstroMilano#22]
Turns out... Updating the humidity records file twice a second isn't such a great idea...
The file gets huuuuge after a while.

I'll do some calculations and see how big the file gets after 3 hours.

**Comment by TheBlocks** [comment]
After some quick calculations (probably wrong), here are the results:
If we run the program for 3 hours:

60Mb for date, month and time + "Humidity: " humidity data

80Mb for same as above but with also "Pressure: "


I'm assuming we are using ASCII. Using Unicode will double file size, I think. (Since ASCII = 8bits per character, Unicode = 16bits per character)

**Comment by TheBlocks** [comment]
Found a way to have less characters in file. Will calculate soon.

**Comment by MobFactory** [comment]
Haha. I dont think we can handle that. But we dont need to.
See all we need to do is store the values for the baseline. Then if the value goes significantly above the baseline for more than 2 seconds (or whatever value we chose) we register that as an astronaut being present.
We dont have to store that data.
That being said... We're using unicode because the is the ESA not NASA. Let's stick to eu standards.

**Comment by TheBlocks** [comment]
Let's use UTF-8, since we're not benefitting from UTF-16. Plus, file sizes are smaller.
